import type { Feed, FeedItem } from "@feedify/core";
const now=Date.now();const iso=(h:number)=>new Date(now-h*3600_000).toISOString();
export const demoFeeds:Feed[]=[
{id:"feed_tantraloka",slug:"tantraloka-daily",creatorId:"demo_creator",creatorName:"Feedify Studio",name:"Tantrāloka Daily",description:"One source-grounded insight from Abhinavagupta's Tantrāloka, distilled without generic spirituality.",emoji:"◉",visibility:"public",version:1,program:{objective:"Distill Tantraloka",mode:"distill",include:["tantraloka","abhinavagupta","recognition"],exclude:["generic"],rankFor:["source fidelity"],voice:"clear and precise",maxItemsPerRun:1,minScore:.45,sourceStrictness:.98,noveltyWeight:.9},sources:[],subscriberCount:3842,subscribed:true,createdAt:iso(200),updatedAt:iso(1)},
{id:"feed_shopify",slug:"shopify-alpha",creatorId:"demo_creator",creatorName:"Feedify Studio",name:"Shopify Alpha",description:"Only Shopify developments with a credible product, distribution or agent-commerce implication.",emoji:"↗",visibility:"public",version:1,program:{objective:"Shopify alpha",mode:"curate",include:["shopify","api","agent"],exclude:["generic"],rankFor:["novelty","actionability"],voice:"high signal",maxItemsPerRun:8,minScore:.48,sourceStrictness:.7,noveltyWeight:.9},sources:[],subscriberCount:9174,subscribed:true,createdAt:iso(200),updatedAt:iso(1)},
{id:"feed_buddha",slug:"buddha-online",creatorId:"demo_creator",creatorName:"Feedify Studio",name:"Buddha Online",description:"Playful Buddhist insights grounded in textual themes rather than invented quotations.",emoji:"☼",visibility:"public",version:1,program:{objective:"Buddha online",mode:"generate",include:["buddha"],exclude:["fake quote"],rankFor:["source fidelity"],voice:"dry playful",maxItemsPerRun:1,minScore:.4,sourceStrictness:.95,noveltyWeight:.8},sources:[],subscriberCount:12820,subscribed:true,createdAt:iso(200),updatedAt:iso(1)}];
export const demoItems:FeedItem[]=[
{id:"i1",feedId:"feed_tantraloka",feedSlug:"tantraloka-daily",feedName:"Tantrāloka Daily",feedEmoji:"◉",feedVersion:1,kind:"summary",title:"Recognition isn't acquiring something new.",body:"Liberation can be framed less as manufacturing a superior state and more as recognizing the awareness already performing every attempt at self-improvement. The interesting word is pratyabhijñā: recognition.",provenance:[{sourceId:"c",sourceType:"corpus",sourceLabel:"Tantrāloka study corpus",excerpt:"Recognition framework"}],createdAt:iso(2),repostCount:12,likeCount:34,commentCount:4},
{id:"i2",feedId:"feed_shopify",feedSlug:"shopify-alpha",feedName:"Shopify Alpha",feedEmoji:"↗",feedVersion:1,kind:"synthesis",title:"Watch for primitives that delete a human-only step.",body:"The agent-commerce releases worth tracking are often tiny APIs that make discovery, authorization or execution machine-readable. Rank the capability change, not the announcement volume.",provenance:[{sourceId:"x",sourceType:"x_search",sourceLabel:"X discovery"}],createdAt:iso(4),repostCount:27,likeCount:66,commentCount:8},
{id:"i3",feedId:"feed_buddha",feedSlug:"buddha-online",feedName:"Buddha Online",feedEmoji:"☼",feedVersion:1,kind:"generated",title:"Your brain has invented quote-posting.",body:"The unpleasant thing happened once. Rehearsing it seventeen times is the mind generously providing syndication. Notice the first arrow; then notice the distribution network for the second.",provenance:[{sourceId:"b",sourceType:"corpus",sourceLabel:"Sallatha Sutta theme"}],createdAt:iso(6),repostCount:49,likeCount:118,commentCount:11}
];
