import type { DatabaseShape, Feed, FeedItem, OutputChannel } from "@feedify/core";
import { defaultOutputs, heuristicCompile, stableId } from "@feedify/core";

const now = Date.now();
const iso = (hoursAgo:number) => new Date(now-hoursAgo*3600_000).toISOString();

function feed(partial: Partial<Feed> & Pick<Feed,"id"|"slug"|"name"|"description"|"emoji">): Feed {
  const prompt=partial.program?.objective || partial.description;
  return {creatorId:"demo_creator",creatorName:"Feedify Studio",visibility:"public",version:1,program:partial.program || heuristicCompile(prompt),sources:partial.sources||[],subscriberCount:partial.subscriberCount||0,createdAt:iso(240),updatedAt:iso(1),...partial};
}

export const seedFeeds: Feed[] = [
  feed({id:"feed_tantraloka",slug:"tantraloka-daily",name:"Tantrāloka Daily",emoji:"◉",description:"One source-grounded insight from Abhinavagupta's Tantrāloka, distilled without generic spirituality.",subscriberCount:3842,program:{...heuristicCompile("Distill the Tantraloka into one surprising daily insight. Keep Sanskrit terms and stay source faithful."),mode:"distill",maxItemsPerRun:1},sources:[{id:"tantra-corpus",type:"corpus",label:"Tantrāloka study corpus",items:[{id:"recognition",title:"Recognition rather than acquisition",text:"A central Śaiva move is to frame liberation not as producing an absent state but as the recognition of the nature of consciousness already operative in experience. Practice therefore changes the mode of recognition rather than manufacturing consciousness itself.",citation:"Tantrāloka / Pratyabhijñā conceptual context"},{id:"means",title:"The means can dissolve into the goal",text:"Tantric classifications of upāya distinguish modes of practice by how much conceptual or embodied mediation is required. The striking implication is that the highest 'means' approaches immediacy: method becomes progressively transparent to the awareness it discloses.",citation:"Tantrāloka, upāya framework"}]}]}),
  feed({id:"feed_shopify",slug:"shopify-alpha",name:"Shopify Alpha",emoji:"↗",description:"Only Shopify developments with a credible product, distribution or agent-commerce implication.",subscriberCount:9174,program:{...heuristicCompile("Highest signal Shopify alpha: APIs, MCPs, agent commerce, merchant pain and buildable opportunities. Exclude generic AI commentary."),mode:"curate",maxItemsPerRun:8},sources:[{id:"x-shopify",type:"x_search",query:"shopify (agent OR MCP OR API OR checkout OR commerce) -filter:replies",product:"Latest",label:"X discovery"}]}),
  feed({id:"feed_buddha",slug:"buddha-online",name:"Buddha Online",emoji:"☼",description:"Playful, concise Buddhist insights grounded in early textual themes rather than invented quotations.",subscriberCount:12820,program:{...heuristicCompile("Buddha posting funny concise insights grounded in Buddhist teachings. Never invent quotes."),mode:"generate",maxItemsPerRun:1},sources:[{id:"buddha-corpus",type:"corpus",label:"Early Buddhist themes",items:[{id:"arrow",title:"The second arrow",text:"Pain can occur without invitation; the mind's proliferation around pain can add a second layer of suffering. The practical distinction is between the immediate event and the extra story constructed around it.",citation:"Sallatha Sutta theme"},{id:"raft",title:"The raft",text:"Teachings function as instruments for crossing, not possessions to carry indefinitely. A useful doctrine can become another attachment when treated as identity rather than method.",citation:"Alagaddūpama Sutta raft simile"}]}]}),
  feed({id:"feed_github",slug:"new-weird-github",name:"New Weird GitHub",emoji:"⌘",description:"Unusual open-source primitives that create new things a solo builder can suddenly do.",subscriberCount:6210,program:{...heuristicCompile("Find new weird GitHub projects and technical primitives with surprising build opportunities."),mode:"curate",maxItemsPerRun:6},sources:[{id:"github-search",type:"github_search",query:"stars:>20 pushed:>2026-08-01",sort:"updated",order:"desc",label:"GitHub discovery"}]})
];

function item(feedId:string, slug:string,name:string,emoji:string,hours:number,title:string,body:string,sourceLabel:string,sourceUrl?:string):FeedItem{return{id:stableId(feedId,title),feedId,feedSlug:slug,feedName:name,feedEmoji:emoji,feedVersion:1,kind:"summary",title,body,provenance:[{sourceId:stableId("seed",sourceLabel),sourceType:"corpus",sourceLabel,sourceUrl,excerpt:body.slice(0,180)}],createdAt:iso(hours),repostCount:Math.floor(80/(hours+2)),likeCount:Math.floor(220/(hours+2)),commentCount:Math.floor(30/(hours+2))};}

export const seedItems: FeedItem[] = [
  item("feed_tantraloka","tantraloka-daily","Tantrāloka Daily","◉",2,"Recognition isn't acquiring something new.","Liberation can be framed less as manufacturing a superior state and more as recognizing the awareness already performing every attempt at self-improvement. The technical interest is pratyabhijñā: recognition changes what experience is understood to be without requiring consciousness to be produced.","Tantrāloka study corpus"),
  item("feed_shopify","shopify-alpha","Shopify Alpha","↗",4,"A commerce primitive matters when it deletes a human-only step.","The interesting agent-commerce releases aren't the loudest AI announcements. Watch for tiny API or protocol changes that turn a previously manual merchant action into something a machine can discover, authorize or execute. Those are disproportionately likely to create new products before the surrounding market notices.","Feedify synthesis"),
  item("feed_buddha","buddha-online","Buddha Online","☼",6,"Your brain has invented quote-posting.","The unpleasant thing happened once. Rehearsing it seventeen times is the mind generously providing syndication. Notice the difference between the first arrow and the distribution network you built for the second one.","Sallatha Sutta theme"),
  item("feed_github","new-weird-github","New Weird GitHub","⌘",11,"The best repo is sometimes a newly exposed capability, not a finished product.","A tiny adapter that gives agents access to a previously human-only surface can be more commercially important than a polished app with 20,000 stars. Rank repositories by what becomes possible after they exist, not just popularity.","Feedify editorial"),
  item("feed_tantraloka","tantraloka-daily","Tantrāloka Daily","◉",26,"The highest method approaches no method.","The upāya framework gets interesting when methods are ordered partly by how much mediation they require. As mediation falls away, practice begins to look less like manipulating experience and more like immediate recognition. The ladder is useful partly because it can eventually disappear.","Tantrāloka study corpus")
];

const baseOutputs=seedFeeds.flatMap((f)=>defaultOutputs(f,iso(120)));
const advancedOutputs:OutputChannel[]=[
  {id:"out_shopify_x",feedId:"feed_shopify",type:"x_bot",name:"Shopify Alpha X bot",enabled:true,config:{strategy:"smart",dryRun:true,minScore:0.72},createdAt:iso(100),updatedAt:iso(1)},
  {id:"out_shopify_x402",feedId:"feed_shopify",type:"x402",name:"Shopify Alpha paid API",enabled:true,config:{price:"$0.01",network:"eip155:8453",path:"latest"},createdAt:iso(100),updatedAt:iso(1)},
  {id:"out_github_x402",feedId:"feed_github",type:"x402",name:"New Weird GitHub paid API",enabled:true,config:{price:"$0.02",network:"eip155:8453",path:"latest"},createdAt:iso(100),updatedAt:iso(1)},
  {id:"out_tantra_blog",feedId:"feed_tantraloka",type:"blog",name:"Tantrāloka Daily blog",enabled:true,config:{format:"markdown"},createdAt:iso(100),updatedAt:iso(1)},
  {id:"out_tantra_report",feedId:"feed_tantraloka",type:"report",name:"Tantrāloka weekly report",enabled:true,config:{cadence:"weekly"},createdAt:iso(100),updatedAt:iso(1)}
];

export const seedDatabase: DatabaseShape={feeds:seedFeeds,items:seedItems,subscriptions:[{userId:"demo",feedId:"feed_tantraloka",createdAt:iso(100)},{userId:"demo",feedId:"feed_shopify",createdAt:iso(90)},{userId:"demo",feedId:"feed_buddha",createdAt:iso(80)},{userId:"demo",feedId:"feed_github",createdAt:iso(70)}],reposts:[],feedback:[],outputs:[...baseOutputs,...advancedOutputs],deliveries:[]};
